language: php

php:
# - 7.0
  - 7.1
# - 7.2

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - composer validate

before_script:
#  - if [ -n "${SYMFONY_VERSION}" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi;
#  - composer update ${COMPOSER_FLAGS} --prefer-dist
#  - export TZ=Europe/Paris

script:
  - echo "Hai!"
#  - ./vendor/bin/phpstan analyze --level=1 -c phpstan.neon lib/
#  - ./vendor/bin/phpunit
#  - php bin/phpbench run --report=env --progress=dots --store
#  - php bin/phpbench run --iterations=1 --revs=1 --config=extensions/dbal/benchmarks/phpbench.json --progress=dots

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env:
      - COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: 
      - SYMFONY_VERSION=^3.0
      - EXECUTE_DEPLOYMENT=true

before_deploy:
    - ./.travis/before-deploy.sh

deploy:
    edge:
        branch: v1.8.47
    provider: pages
    skip-cleanup: true
    file: 
        - phpbench.phar
        - phpbench.phar.version
    target-branch: gh-deploy-test
    github-token: 
        secure: "cVKcMHHv6MV1HiP78hYPyBx6VIy+DzIv6HS0QM/g3gHnE7EWopu9mQjku2DQtQWAjqVrIPL3ClvZxJH5MjDd4/kB6kWQDGX5O2+CaqzhaJgSpT0htFLbiClqK1uvl2QnHoqwfnhIux230AWDtQfod1g1p60nryo65pLG0HGHqXU="
    keep-history: true
    on:
      branch: gh-deploy
      condition: $EXECUTE_DEPLOYMENT=true
